# Generated by Django 4.1.2 on 2022-10-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_categoria_alter_movimento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='data',
            field=models.DateField(),
        ),
    ]
