# Generated by Django 4.1.2 on 2022-11-17 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_movimento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='valor',
            field=models.FloatField(default=datetime.datetime(2022, 11, 17, 18, 38, 59, 534024)),
        ),
    ]
