# Generated by Django 4.1.2 on 2022-11-17 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_movimento_data_alter_movimento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 18, 42, 39, 871244)),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='valor',
            field=models.FloatField(),
        ),
    ]
